name: Deploy

on:
  # Triggers the workflow on 'push on main branch'.
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build_push_image:
    uses: ./.github/workflows/workflow_image.yml
    secrets: inherit

  checkout_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          echo "matrix<<EOF"  >> $GITHUB_OUTPUT
          echo "$(cat ./environments/run-matrix.json)"  >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  deploy:
    needs: [ build_push_image, checkout_matrix ]
    name: Deploy
    strategy:
      matrix: ${{fromJson(needs.checkout_matrix.outputs.matrix)}}
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/workflow_deploy.yml
    with:
      image-tag: ${{ needs.build_push_image.outputs.image-tag }}
      deploy-env: ${{ matrix.chalocodekare-env }}
    secrets: inherit