name: Validate Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_pr:
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit